import ast
def safe_calculate(func):
    def wrapper(expression):
        try:
            parsed_expression = ast.parse(expression, mode='eval')
            eval(compile(parsed_expression, filename='', mode='eval'))
            result = func(expression)
            return result
        except (SyntaxError, ZeroDivisionError, ValueError) as e:
            print(f"Error: {e}")
            return None
    return wrapper
def calculate(expression):
    return eval(expression)
result = calculate("10 / 2 + 3 * 5")
print(result)
result = calculate("10 / 0")  # Ділення на нуль
print(result)
result = calculate("10 + 'abc'")  # Невірний тип даних
print(result)
